# Generated by Django 2.1.5 on 2019-02-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190210_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=5),
            preserve_default=False,
        ),
    ]
